<?php

declare(strict_types=1);

namespace Framework\Database;

/**
 * Contract every database driver must implement (MySQLConnection, PostgresConnection, etc).
 * Keeping this as an interface — not an abstract class — mirrors the framework's
 * MiddlewareInterface pattern, so drivers can be swapped by simply binding a different
 * concrete class to this interface in the Container.
 * @package Framework\Database
 */
interface ConnectionInterface
{
    /**
     * Runs a SELECT-style query and returns all matching rows.
     *
     * @param string $sql Parameterized SQL (use ? or :named placeholders).
     * @param array $bindings Values to bind to the placeholders.
     * @return array List of rows, each row as an associative array.
     */
    public function query(string $sql, array $bindings = []): array;

    /**
     * Runs a single-row SELECT-style query and returns just the first row, or null if none.
     *
     * @param string $sql
     * @param array $bindings
     * @return array|null
     */
    public function queryOne(string $sql, array $bindings = []): ?array;

    /**
     * Runs an INSERT/UPDATE/DELETE-style statement and returns the number of affected rows.
     *
     * @param string $sql
     * @param array $bindings
     * @return int Number of affected rows.
     */
    public function execute(string $sql, array $bindings = []): int;

    /**
     * Returns the auto-increment ID generated by the most recent INSERT statement.
     *
     * @return string
     */
    public function lastInsertId(): string;

    /**
     * Starts a transaction.
     *
     * @return void
     */
    public function beginTransaction(): void;

    /**
     * Commits the current transaction.
     *
     * @return void
     */
    public function commit(): void;

    /**
     * Rolls back the current transaction.
     *
     * @return void
     */
    public function rollBack(): void;
}